from typing import Protocol, Iterable

from numpy import ndarray

from ..model import Model

class SelectorModel(Model, Protocol):

    def ensemble_selector(self) -> bool: ...
    def selections(self, X: ndarray) -> ndarray: ...
    def competences(self, X: ndarray) -> ndarray: ...
    def classifiers(self) -> Iterable[Model]: ...
